### ISSUE TITLE
Create announcement section with excel sheet

### ISSUE THREAD

**Issue by psyprofmichele** [contact-research-network/webpage#3]
Create an announcement section that can be updated via an excel sheet. For this identify how an image can be displayed via an imageurl.

**Comment by LukasWallrich** [comment]
Image download from Google Drive _might_ work like this - if so, that would make it easy to include pictures: https://stackoverflow.com/a/39225272

@psyprofmichele already created a template spreadsheet: https://docs.google.com/spreadsheets/d/19ylN6fWPO_aMLx9pPBacXodXKEih42iNmceInhMT6Zg/edit?gid=0#gid=0

**Comment by LukasWallrich** [comment]
That link does not work inside an HTML file (as ChatGPT claims) - but can be used to download. E.g, with this code:

```r
library(httr)

# Define the URL and destination file path
url <- "https://drive.google.com/uc?export=download&id=15Gs3ZWBROhsATHUGp8_K9RefR1KN9d_O"
destfile <- "downloaded_file"

# Download the file
GET(url, write_disk(destfile, overwrite = TRUE))

# Check if the file is downloaded
if (file.exists(destfile)) {
  message("File downloaded successfully.")
} else {
  message("File download failed.")
}
```

**Comment by LukasWallrich** [comment]
Never closed this - but it now works from the URL above
